### ISSUE TITLE
GESTIONE PROGRAMMI

### ISSUE THREAD

**Issue by Gund77** [lejubila/piGarden#1]
Ciao, 
Mi sono iscritto anche io per descriverti a macroelementi la struttura della routine che ho in mente. anzitutto devo dirti che io nasco programmatore ma non esercito da una vita, quindi mi sono perso il passo generazionale dei nuovi framework tipo laravel, drupal ecc. 
Ovviamente la logica della programmazione rimane e vorrei, appunto, condividere con te la mia idea. Sicuramente mi applicherò e studierò la programmazione BASH per aiutarti nelle modifiche. 

Detto questo, passiamo alla mia idea:

PIGARDEN WEB
------------ 
che funge da coordinatore dovrà in qualche modo (lo vedremo successivamente, non conoscendo Laravel) gestire il PROGRAMMA DI IRRIGAZIONE, che definisce una sequenza di irrigazioni e creerà opportunamente una entry nella CronTable. 

PIGARDEN.SH
-----------
a piGarden, in una nuova funzione "ESEGUI_PROGRAMMA" verranno passate 2 stringhe di valori che verranno convertiti in 2 array (ci sono funzioni già fatte in rete), in questo formato:

- $1     EV1,EV2,EV3, .. ,EVn    
- $2	 T1,T2,T3, .. ,Tn

Dove per EV si intende ovviamente l'elettrovalvola, e con T si intende il tempo di irrigazione in minuti. 

A questo punto un ciclo FOR verrà eseguito per ogni EV del programma e ad ogni iterazione verrà eseguita la funzione IRRIGA che avrà come parametri EVx e Tx

La funzione IRRIGA
------------------
dovendo gestire il tempo di apertura dovrà essere modificata in modo sostanziale, perchè dovranno venire eseguiti 2 cicli FOR DOWN-TO annidati, dove il primo scala i minuti e quello interno, sempre DOWN-TO conta i secondi.
Si fanno i controlli sulla pioggia METEO ONLINE e se OK allora si richiama la funzione OPEN $1 e successivamente partono i 2 cicli annidati.

In ogni iterazione verrà eseguita una istruzione SLEEP 1 che farà attendere un secondo prima di ripeterla; in sostanza è un ciclo di attesa.
Al termine dei 2 cicli verrà ordinato alla EVx di chiudersi con una CLOSE $1. Va da se che la funzione EV_CLOSE non andrà più impostata nella Cron-table quando si opera con un programma perchè di fatto la chiusura è un derivato di Apertura+tempo_irrigazione.

Qui possiamo fare 3 considerazioni: 

1) se si vuole aggiungere un display I2C a raspberry possiamo fare scrivere a monitor quale EV è aperta e quanto tempo manca alla chiusura con una funzione apposita (Write Display EV_ALIASx  TEMPO_RIMANENTE, dove TEMPO_RIMANENTE é il risultato della concatenazione di MIN+":"+SEC, i 2 indici dei cicli FOR. (poi la gestione della visualizzazione è tutta da pensare...)

2) Ad ogni minuto, quindi ad ogni iterazione del ciclo esterno, potremmo controlare il sensore per vedere se sta piovendo, in quel caso forzeremo l'uscita dal ciclo, scriveremo PIOGGIA IN CORSO sul display e usciremo forzatamente dal ciclo. 
 
3) Impostando un parametro nel file.conf possiamo specificare quale tipo di EV abbiamo tra Monostabile e Bistabile e in base a questo parametro gestire opportunamente l'apertura, risolvendo anche il problema a Stefano. Ovviamente in questo caso è auspicabile acquistare un DC-DC 5v to 9v USB per evitare di dover cambiare la Pila 9v ogni mese. Dico 9V ma esistono anche da 12 e 24v... una cosa tipo questa: https://goo.gl/Zwt7T3

Le funzioni OPEN e CLOSE (o decidi il nome che preferisci)
------------------------
Di fatto fanno quello che fanno attualmente EV_OPEN ed EV_CLOSE ma epurate di tutti i controlli, quindi di fatto aprono e chiudono l'elettrovalvola a seconda del parametro TIPO_EV. 
Di fatto è possibile riscrivere EV_OPEN ed EV_CLOSE perchè la logica di controllo viene spostata nella funzione IRRIGA

GESTIONE DELLA PIOGGIA
----------------------
Una possibile evoluzione per la gestione della pioggia è quella di renderla un pochino più "SMART". Se piove 1 ora in estate è sconveniente attendere 1 gg per la prossima irrigazione perchè magari il terreno è asciutto e l'erba può soffrire. 
All'opposto se dovesse piovere a marzo, magari possiamo far attendere 2 o 3 gg prima di irrigare di nuovo.
Questa idea la butto li, va ponderata bene. I sensori di umidità del terreno ci sono ma penso che durino 10 gg prima di ossidarsi e diventare inutili, a meno che non si prenda un sensore professionale (tipo hunter o claber o rainbird) che hanno performance differenti. 

Penso che di carne al fuoco ce ne sia molta a questo punto.
Dimmi che ne pensi...  

Grazie e buona serata, 
Marco

**Comment by Gund77** [comment]
[IRRIGA.txt](https://github.com/lejubila/piGarden/files/994368/IRRIGA.txt)

**Comment by lejubila** [comment]
Ciao @Gund77 e benvenuto.
Innanzitutto non preoccuparti perché anche io attualmente non esercito da programmatore anche se in passato ho lavorato nello sviluppo web e gestionale. Ho avuto diverse esperienze di sviluppo con Laravel ma non sono certo in mago. Quindi tranquillo abbiamo tutti da imparare :)

Complimenti per l'idea e per l'implementazione che hai proposto, veramente ben documentata.

Intanto volevo chiarire che inizialmente piGarden doveva essere un semplice script per aprire e chiudere le elettrovalvole. Per questo avevo deciso di farlo in Bash e non starmi ad imparare un altro linguaggio tipo Python che avrebbe reso tutto più elegante.

La linea di sviluppo che ho cercato di tenere è quella di delegare a piGarden tutta la logica applicativa. Quindi è lui che definisce le elettrovalvole, le schedulazioni, la gestione della pioggia, ecc...
piGardenWeb invece funziona solo da frontend verso piGarden comunicandogli cosa deve fare tramite socket server.

# piGarden

In base a quanto detto sopra la definizione dei gruppi la delegherei al file di configurazione di piGarden. Per ogni gruppo definirei una singola variabile contenente sia l'elenco delle elettrovalvole che il tempo di apertura. Per il nome delle variabili riproporrei la stessa logica usata per le elettrovalvole. Di seguito riporto un esempio:

GRP1_ALIAS="ZONA_ANTERIORE"
GRP1_EV="GIARDINO_ANTERIORE_DX,30,GIARDINO_ANTERIORE_SX,30,GIARDINO_ANTERIORE_CN,30"

GRP1_ALIAS="ZONA_POSTERIORE"
GRP1_EV="GIARDINO_POSTERIORE_DX,30,GIARDINO_POSTERIORE_SX,30,GIARDINO_POSTERIORE_CN,30"

In questo modo abbiamo definito due gruppi, ZONA_ANTERIORE e ZONA_POSTERIORE.
Il gruppo ZONA_ANTERIORE gestirà le elettrovalvole con alias GIARDINO_ANTERIORE_DX, GIARDINO_ANTERIORE_SX e GIARDINO_ANTERIORE_CN dove ognuna rimarrà aperta per 30 minuti.
Il tempo definito di apertura per semplicità lo definirei in minuti, anziché minuti:secondi.

Per quanto riguarda la routine che hai spiegato, io per semplicità manterrei un unico ciclo FOR contando i minuti di apertura indicati nella variabile che definisce il gruppo. Per ogni iterazione del gruppo eseguirei uno sleep di 60 secondi in modo da attendere un minuto.
Prima dell'apertura dell'elettrovalvola secondo me non importa controllare lo stato della pioggia perché questo viene fatto direttamente dalla funzione EV_OPEN. Entrati nel ciclo invece a quel punto si andrebbe eseguito il controllo sul sensore che il servizio online (se abilitati nel file di configurazione) in modo da uscire prematuramente in caso di pioggia.

L'unica cosa che mi preoccupa un po' è che come è concepito lo script rimarrebbe in esecuzione finché non si conclude tutto il ciclo di irrigazione. Se qualcosa va storto durante l'esecuzione e se per qualche ragione lo script viene interrotto c'è il rischio che l'irrigazione rimanga aperta.
Comunque sia una volta impartito l'avvio del gruppo dovrò trovare il modo di fare continuare l'esecuzione  lo script in background in modo che la shell e soprattutto la chiamata socket da piGardenWeb non rimangano appese fino alla fine dell'esecuzione del ciclo di irrigazione.

Mi viene in mente ora che bisognerà gestire anche la chiusura anticipata del ciclo di irrigazione nel caso l'utente lo voglia fare. Per fare questo io gestirei lo stato del gruppo, similmente a come avviene per le elettrovalvole, memorizzandolo in alcuni file dentro la cartella piGarden/state.
All'avvio del ciclo di irrigazione impostiamo lo stato ad 1, in questo modo sappiamo che il ciclo è in esecuzione e possiamo rappresentarlo nell'interfaccia web. 
Se vogliamo fermare anzitempo il programma di irrigazione possiamo impostare lo stato del gruppo con il valore 0 e nel ciclo FOR controllarlo per farlo uscire anticipatamente.
Forse a questo punto contrariamente a come avevo detto prima, conviene reinserire il ciclo dei secondi nel quale controlliamo lo stato per l'eventuale uscita anticipata.

A questo punto direi che andrebbero implementati i seguenti comandi da fare eseguire a piGarden:

- piGarden.sh open_grp alias_grp   # Avvia l'irrigazione del gruppo
- piGarden.sh close_grp alias_grp   # Interrompe l'irrigazione del gruppo impostando lo stato a zero
- piGarden.sh add_cron_open_grp alias m h dom mon dow   # Imposta la schedulazione di apertura del gruppo
- piGarden.sh del_cron_open_grp alias   # Elimina le schedulazioni di un gruppo
- piGarden.sh get_cron_open alias_grp   # Mostra le schedulazioni di un gruppo

Oltre ai comandi da passare allo script vanno implementate le funzioni sopra descritte nelle api per la comunicazione tramite socket server.

# piGardenWeb

Come dicevi nell'interfaccia web dovrà gestire la schedulazione per programmare l'apertura dei gruppi. piGardenWeb comunicherà tramite socket server per leggere e scrivere le schedulazioni nel crontab.

# Varie ed eventuali

- Display I2C, una bella idea, io non ci avevo pensato però per ora lo tralascerei (di carne al fuoco ce n'è tanta). Magari nel ciclo interno possiamo eseguire una funzione per la stampa delle informazioni (orario e gruppo). Questa funzione la definiamo in un file esterno a piGarden.sh, dove sarà possibile implementare da parte dell'utente finale la scrittura su display oppure su altro dispositivo.
- Elettrovalvole monostabili, anche io avevo pensato di inserire un parametro nel file di configurazione e in base a questo agire di conseguenza nelle funzioni EV_OPEN e EV_CLOSE. Per l'alimentazione delle elettrovalvole è sicuramente da escludere la batteria ma dovrà essere utilizzato un alimentatore separato. Non ho esperienza in questo campo e non ho l'hardware su cui fare i test. Non so se il raspberry possa reggere un convertitore DC-DC collegato aull'usb. Come dicevo non ho esperienza.
- Non ho capito bene cosa intendi per la riscrittura delle funzioni OPEN e CLOSE, comunque io lascerei tutto come è ora (anche per retrocompatibilità) e aggiungerei la gestione dei gruppo come descritto sopra. In questo modo l'utente può decidere se programmare le singole zone oppure utilizzare i gruppi.
- Gestione della pioggia, effettivamente così com'è fatta ora è abbastanza rudimentale sarebbe da migliorare.
- Sensori di umidità, anche su questo non ho abbastanza esperienza ma avevo già iniziato ad affrontare il problema [qui](https://forum.raspberryitaly.com/showthread.php?tid=2188&pid=12239), anche secondo me i sensori in commercio hanno vita breve e poi c'è il problema della connessione con il raspberry che dovrebbe essere wireless.

Per ora e tutto,
spero di essermi riuscito a spiegare bene.

Complimenti ancora per l'idea.
A presto.

**Comment by Gund77** [comment]
Ciao!
Diciamo che questo progetto mi ha affascinato sin da subito. Come ti dicevo negli anni ho perso la pratica, ma l'indole da sistemista-programmatore del liceo è rimasta... ma torniamo a noi. 

Per quanto riguarda l'Hardware comunque non ci penserei più di tanto, e lo demanderei al singolo utente finale. Nella fattispecie io ho acquistato un UPS-shield ( https://goo.gl/5xuSSL ) che ha 2 uscite USB, una per Raspberry e una per il modulo Step-UP 5v to 9V che ovviamente dovrò prima testare da sola. 
Questo permette di non collegare nulla al raspy tenendolo in sicurezza, e di avere una batteria di qualche ora in caso vada via la corrente. La cosa veramente bella sarebbe quella di riuscire ad avere il controllo dello stato dell'alimentazione per aggiungere una ulteriore controllo che subordini l'apertura con la presenza di tensione. Detto questo per me è difficile che si debba irrigare per più di 1 ora, il mio programma più lungo era di 50 minuti per l'ala gocciolante della siepe.

Come linea di principio comprendo bene le motivazioni della tua premessa, e non so se hai in mente un porting verso Python (credo si possa ancora fare in modo relativamente agevole in questa versione) ma, porting o no, credo sia da valutare la possibilità di sfruttare il DB come punto di contatto tra i due moduli 
(PiGardenWeb  scrive, piGarden legge) per avere la possibilità di poter gestire anche informazioni storiche, ad esempio:

- Creazione dei programmi da piGardenWeb
- Memorizzazione degli eventi meteo (attualmente ho notato che, se si riavvia, il sistema non ricorda l'ultima volta che ha piovuto) 
- Tabelle di appoggio per passaggio dati
- Log nel DB consultabile anche da piGardenWeb

Perdonami se ritorno sulla questione, ma utilizzare il DB credo abbia dei vantaggi da considerare. Ovviamente si potrà eventualmente realizzare anche più in là nel tempo.


Torniamo alle macro-voci:

piGarden
---------

Ok per la definizione dei gruppi nel file .Conf
Il calcolo del tempo in secondi l'ho fatto per una questione puramente legata al  display, ma come hai poi valutato anche tu la lascerei per l'eventuale comando di stop "d'emergenza". Il display è un vezzo, è vero, ma ci ho pensato perchè in casa ho un quadro elettrico a 3 linee in barra DIN e sarebbe bello poter vedere chi sta irrigando e quanto tempo manca. 

Il controllo della pioggia nel ciclo era per evitare di irrigare nel momento in cui si mette a piovere a programma iniziato.

Per evitare che l'irrigazione rimanga aperta, se si riuscisse a salvare la schedulazione anche nel DB, possiamo fare girare una routine a intervalli di 5 minuti che esegue una query e chiude tutte le EV che non devono essere in esecuzione in quel momento, se sono aperte. 




piGardenWeb 
-----------

Tutto chiaro


VARIE ED EVENTUALI 
------------------

- Display sicuramente più avanti, e sicuramente in un file esterno, perchè la gestione più semplice la si ottiene con Python, che verrà poi richiamato da BASH. Io comunque mi ci metterò a giocare appena mi arriva e vedo se riesco a creare una API di gestione del display (questo comporterà una rimappatura delle porte GPIO utilizzate sul raspy perchè i pin dedicati al seriale sono usate dalle EV attualmente)

- Tipo elettrovalvola: è chiaro il metodo di funzionamento. L'alimentatore può essere anche AC-DC (visto che di solito sono a 12 o 24v), tanto più che se cade la corrente la valvola si chiuderebbe comunque. 

- La riscrittura delle funzioni OPEN e CLOSE era per strutturare in una unica istruzione l'apertura di tutte e 2 le tipologie di EV; cioè, richiami la funzione OPEN EVx e indipendentemente dal tipo (perchè viene gestito nella funzione in base al parametro) l'elettrovalvola si chiude o si apre. In sostanza rendi "atomica" una serie di istruzioni, è solo per pulizia del codice. 

EV_OPEN poi conterrà anche altri controlli, tipo pioggia.

Grazie a te!
a presto

**Comment by lejubila** [comment]
Ciao,
rispondo solo dopo diversi giorni ma purtroppo ho avuto un po' di problemini.

Allora......
attualmente no non ho intenzione di passare a python, si tratterebbe di riscrivere tutto e sinceramente con il poco tempo che ho e tutto il tempo che ho impiegato ad arrivare a questo punto non mi va di reinventare la ruota.
Discorso database, capisco benissimo i vantaggi che ci possono essere ma per ora non ho intenzione di utilizzarlo per varie motivazioni:
- il db più naturale da usare sarebbe mysql, ma su raspberry dove le risorse sono limitate (specialmente sui vecchi modelli come il mio) diventa un po problematico gestirlo
- un db mysql su sdcard non mi sembra il massimo 
- gestione del db da bash, non è impossibile ma bisognerebbe appoggiarsi a script esterni e si complicherebbe il tutto.

Riguardo i vantaggi che mi elencavi

> Creazione dei programmi da piGardenWeb

Ho una mezza idea di cambiare struttura al file di configurazione in modo che sia posizionato in una sottodirectory di pigarden (e non più sotto etc). Ci sarebbero più file di configurazione ognuno avrebbe il proprio ruolo e conterrebbe informazioni ben specifiche (uno per le elettrovalvole, uno per i path, uno per i gruppi, ecc...).
In questo modo sarebbe controllabile da piGarden e questo tramite apposite funzioni potrebbe creare/variare direttamente i file di configurazione. Fatto questo si potrebbe sviluppare delle api per l'interfacciamento via socket server e quindi controllabili da piGardenWeb. In questo modo quest'ultimo avrebbe accesso e controllo di tutta configurazione e quindi potrebbe gestire anche direttamente al configurazione dei gruppi.

> Memorizzazione degli eventi meteo (attualmente ho notato che, se si riavvia, il sistema non ricorda l'ultima volta che ha piovuto)

Lo stato della pioggia viene memorizzato in due file sotto piGarden/state (uno per il sensore e uno per il serviazio online). La perdita dell'informazione è dovuta al fatto ce con l'inizializzazione di pigarden tutto il contenuto della directory state viene cancellato. Per non perdere l'informazione basta non fare cancellare i due file.

> Tabelle di appoggio per passaggio dati

piGardenWeb fa una chiamata ogni 20 secondi temite socket server e ad ogni cambio di pagina. Con questa chiamata recupera lo stato di piGaden, in questo modo possono essere passati i dati necessari se opportuno.

> Log nel DB consultabile anche da piGardenWeb

Effettivamente ci avevo pensato in passato, potrebbe essere implementata un api per il passaggio dei log tramite socket server ma è da verificare.


## piGarden

> Ok per la definizione dei gruppi nel file .Conf
> Il calcolo del tempo in secondi l'ho fatto per una questione puramente legata al display, ma come hai poi valutato anche tu la lascerei per l'eventuale comando di stop "d'emergenza". Il display è un vezzo, è vero, ma ci ho pensato perchè in casa ho un quadro elettrico a 3 linee in barra DIN e sarebbe bello poter vedere chi sta irrigando e quanto tempo manca.

Nella risposta precedente il ciclo dei secondi avevo detto che si poteva saltare, ma poi ripensandoci l'avevo reintrodotto, servirebbe anche per verificare se nel frattempo qualcuno abbia fermato manualmente l'irrigazione del gruppo oppure se il sensore abbia riscontrato della pioggia. Questo si farebbe verificando il contenuto del file di stato relativo al gruppo. Il file di stato verrebbe valorizzato con un apposito valore quando viene fermata l'irrigazione per un qualsiasi motivo.


> Il controllo della pioggia nel ciclo era per evitare di irrigare nel momento in cui si mette a piovere a programma iniziato.

Come detto sopra il controllo sulla chiusura verrebbe fatto nel ciclo controllando il file di stato del gruppo

> Per evitare che l'irrigazione rimanga aperta, se si riuscisse a salvare la schedulazione anche nel DB, possiamo fare girare una routine a intervalli di 5 minuti che esegue una query e chiude tutte le EV che non devono essere in esecuzione in quel momento, se sono aperte.

Questa funzione esiste già e non necessita del db e lo gestisce il seguente crontab (che hai anche te se hai lanciato il setup iniziale dall'interfaccia web)
`*/5 * * * * /home/pi/piGarden/piGarden.sh close_all_for_rain`
Questo viene eseguito ogni 5 minuti e controlla i file di stato della pioggia e se opportuno chiude tutte le elettrovalvole.
Nel nostro caso andrebbe modificato e aggiunto che venga cambiato anche il valore nel file di stato dei gruppi in modo che poi questi vengano chiusi grazie al controllo che viene eseguito nel ciclo dei secondi.

## VARIE ED EVENTUALI

Relativamente alle alla riscrittura dei delle funzioni di apertura/chiusura preferisco lasciare tutto come è attualmente e che ogni funzione abbia un suo ruolo. Soprattutto per non stravolgere l'utilizzo a chi già lo usa, perché non è detto che tutti vogliano utilizzare la funzione dei gruppi ma magari prferiscono soltanto l'apertura/chiusura delle singole elettrovalvole.

## Conclusioni

Concludendo quoto dal commento precedente le funzioni che secondo me andrebbero implementate per la gestione dei gruppi:

> 
> piGarden.sh open_grp alias_grp # Avvia l'irrigazione del gruppo
> piGarden.sh close_grp alias_grp # Interrompe l'irrigazione del gruppo impostando lo stato a zero
> piGarden.sh add_cron_open_grp alias m h dom mon dow # Imposta la schedulazione di apertura del gruppo
> piGarden.sh del_cron_open_grp alias # Elimina le schedulazioni di un gruppo
> piGarden.sh get_cron_open alias_grp # Mostra le schedulazioni di un gruppo
> Oltre ai comandi da passare allo script vanno implementate le funzioni sopra descritte nelle api per la comunicazione tramite socket server.

Oltre a queste bisognerebbe variare anche il controllo sulla pioggia fatto con la funzione _close_all_for_rain_ come dicevo sopra.

**Comment by Gund77** [comment]
Buongiorno David, 
Tranquillo, per il passaggio a Python sono conscio che riscrivere tutto è un lavoraccio, ci avevo pensato perchè ho visto che ci sono dei tool di traduzione che a questo punto della vita dello script potevano aiutare, ma va bene così. Concordo anche sulle tue valutazioni circa l'uso di MySql come DB, non è sicuramente il massimo. su SD.
I file di configurazione "specializzati" è una bella idea e, correggimi se sbaglio, l'idea è quella di poterli modificare da interfaccia WEB, il che si traduce in 2+1 funzioni: 
- LEGGI_CONFIG <nomefile>: legge il file e lo mette in un campo TEXT
- SCRIVI_CONFIG <nomefile>: prende il contenuto del campo TEXT e lo scrive nel file
il tutto corredato da una funzione di "servizio"
- RIAVVIA_SERVIZI che ricarica la nuova configurazione

Riguardo il meteo sto studiacchiando una possibile soluzione che tenga conto di alcuni fattori ed un minimo di storia del meteo degli ultimi 3-4 giorni (se arriviamo da 3 gg di piogga, potrebbe non essere necessario innaffiare, ma se ha piovuto per 1 ora in agosto, potrebbe essere necessario).

Ah, grazie per la dritta, effettivamente non avevo notato la cancellazione del file meteo nella funzione di inizializzazione.

Ok, mi pare che le specifiche siano state tutte definite!

Ti ringrazio ancora per il lavoro egregio. 
Se posso fare qualcosa non esitare a dirmelo.

Ciao,
Marco

**Comment by androtto** [comment]
Ciao a tutti
ho pensato di lasciare così com'è l'attuale struttura di piGarden, mentre ho introdotto piGardenSched che si sostituisce al crontab. E' lui che esegue l'eccitazione delle elettrovalvole in sequenza.
Ho aperto un tread specifico per piGardenSched. Vi invito a leggerlo e a commentare!
Grazie
ciao
A

**Comment by lejubila** [comment]
Chiudo la Issue in quanto con l'avvento di piGardenSched parte delle proposte di @Gund77 sono state risolte.
