### ISSUE TITLE
Driver per Sonoff ...

### ISSUE THREAD

**Issue by lejubila** [lejubila/piGarden#12]
_From @debugasm on May 20, 2018 7:32_

Sarebbe interessante avere il driver per i rele remoti che ormai sono diffusissimi : "Sonoff".

Con semplici comandi si possono aprire/chiudere rele connessi alla rete WiFi di casa.

La lista dei comandi si trova qui: [Comandi](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#web)

Semplici comandi HTTP "GET"

```
http://sonoff/cm?cmnd=Power[x]%20TOGGLE
http://sonoff/cm?cmnd=Power[x]%20On
http://sonoff/cm?cmnd=Power[x]%20off
http://sonoff/cm?user=admin&password=joker&cmnd=Power[x]%20Toggle
```

Per un uso senza password e 4 rele [Sonoff 4 Ch.](https://www.itead.cc/wiki/Sonoff_4CH):

```
http://192.168.x.x/cm?cmnd=Power1%20On
http://192.168.x.x/cm?cmnd=Power2%20On
http://192.168.x.x/cm?cmnd=Power3%20On
http://192.168.x.x/cm?cmnd=Power4%20On

http://192.168.x.x/cm?cmnd=Power1%20Off
http://192.168.x.x/cm?cmnd=Power2%20Off
http://192.168.x.x/cm?cmnd=Power3%20Off
http://192.168.x.x/cm?cmnd=Power4%20Off
```

Per rendere piGarden/piGardenWeb completo secondo me non dovrebbe mancare la gestione dei Sonoff.

_Copied from original issue: lejubila/piGardenWeb#6_

**Comment by lejubila** [comment]
@debugasm 
sto cercando di scrivere un driver per i moduli sonoff ma non avendo nessun modulo sotto mano avrei bisogno del tuo supporto.
E' fondamentale di capire le varie tipologie di response generate a seguito delle chiamate http per impartire un comando al modulo.
In particolare, quando la chiamata va a buon fine e quando fallisce. Magari vengono restituiti dei codici http specifici ?
Oppure vengono restituiti dei json ?

**Comment by lejubila** [comment]
_From @debugasm on May 20, 2018 9:25_

Ho fatto due prove con "wget".

Per rele "ON" :
```
http://192.168.x.x/cm?cmnd=Power1%20On
```
Si otteine in "json" "OK" di risposta:
```
{"POWER1":"ON"}
```

Per rele "OFF" :
```
http://192.168.x.x/cm?cmnd=Power1%20Off
```
Si otteine in "json" "OK" di risposta:
```
{"POWER1":"OFF"}
```

Invio comando non valido o malformato:
```
http://192.168.x.x/cm?cmnd=Pxxxxe1%20Off
```
Si otteine in "json" "Unknown" di risposta:
```
{"Command":"Unknown"}
```

Inviando il comando "wget" restituisce "echo $? = 0" esecuzione ok.

Inviando il comando "wget" ad un indirizzo non valido si ottiene il classico "echo $? = 4" timeout.

Per meglio darti una mano posso controllare sul codice sorgente del firmware per ottenere tutte le possibili risposte "json".

Controllo.

**Comment by lejubila** [comment]
Quindi se ho capito bene viene restituito un json con il nome del relè e il relativo stato assunto da questo.
Se effettivamente è così faccio una verifica su questo stata condizione per capire se la chiamata è andata a buon fine.

**Comment by lejubila** [comment]
_From @debugasm on May 20, 2018 9:46_

Esattamente, viene restituito un "json" con lo stato assunto dal rele dopo l'ultimo comando.
```
{"USCITA":"STATO"}
```

**Comment by lejubila** [comment]
Ho fatto una prima implementazione del driver.

Per definire le elettrovalvole devi prima definire il modulo sonoff (o i moduli se sono più di uno). Lo fai inserendo nel file di configurazione delle variabili tipo queste:
```
SONOFF1_IP="192.168.1.1"
SONOFF1_USER="user"
SONOFF1_PWD="pwd"
```
In questo modulo hai definito il modulo SONOFF1 che hai l'ip 192.168.1.1 a cui si può accedere con utente "user" e password "pwd". Se il modulo non ha credenziali di accesso imposti assegni una stringa vuota.

Per definire l'elettrovalvola imposta dei parametri tipo i seguenti:
```
EV1_ALIAS="Sonoff_Power1"
EV1_GPIO="drv:sonoff_tasmota_http:SONOFF1:Power1"

EV2_ALIAS="Sonoff_Power2"
EV2_GPIO="drv:sonoff_tasmota_http:SONOFF1:Power2"

EV3_ALIAS="Sonoff_Power3"
EV3_GPIO="drv:sonoff_tasmota_http:SONOFF1:Power3"

EV4_ALIAS="Sonoff_Power4"
EV4_GPIO="drv:sonoff_tasmota_http:SONOFF1:Power4"
```
La stringa che indica il GPIO riporta i valori che definiscono il driver e i parametri da passargli. Questi sono separati da i due punti e sono i seguenti:
drv = indica di utilizzare un driver
sonoff_tasmota_http = driver da utilizzare
SONOFF1 = modulo sonoff da utilizzare 
Power4 = nome del relè sonoff da utilizzare

Se tutte le elettrovalvole sono monostabili puoi impostare il valore EV_MONOSTAVLE=1.
Se solo alcune elettrovalvole sono monostabili le puoi definire facendo riferimento alla singola elettrovalvola, es: EV1_MONOSTABLE=1 indica che l'elettrovalvola 1 è monostabile.

Se gestisci delle elettrovalvole bistabili devi definire i relè che gestiscono l'inversione di polarità così:
SUPPLY_GPIO_1="drv:sonoff_tasmota_http:SONOFF1:Power5"
SUPPLY_GPIO_2="drv:sonoff_tasmota_http:SONOFF1:Power6"
In questo caso i relè che gestiscono i l'inversione di polarità sono quelli Power5 e Power6 del modulo SONOFF1.

Per vedere i log dei driver definisci nel file di configurazione il file dove redirigere l'output così:
LOG_OUTPUT_DRV_FILE="/tmp/piGarden.drv.log"


Fammi sapere con questa prima implementazione riesci ad avere dei risultati.

**Comment by lejubila** [comment]
Dimenticavo, il dirver è nel brench "drv",
per avere queste ultime modifiche devi aggiornare e passare nel brench drv in questo modo

```
git checkout drv
git pull
```

**Comment by lejubila** [comment]
Vedo solo ora dal link che mi hai fornito ( https://www.itead.cc/wiki/Sonoff_4CH ) che il relè del modulo sono solo a due vie (e non a tre come quelli che avevo usato sul raspberry), in più hanno un polo i comune (L-in). 
Questo impedisce di potere utilizzare i relè del sonoff per l'inversione di polarità per gestire le elettrovalvole bistabili. Quindi i parametri SUPPLY_GPIO_1 e SUPPLY_GPIO_2 non potranno essere definiti.

Non ho capito bene invece a cosa servono i due gruppi di piedini nominati N e GND.

**Comment by lejubila** [comment]
_From @debugasm on May 21, 2018 7:33_

Grazie mille per l'impegno immediato. 

Ho qualche minuti di tempo quindi ho installato la nuova versione ma ho dovuto utilizzare un altro comando per ottenre "piGarden":

```
git clone --branch drv https://github.com/lejubila/piGarden.git
```

Ho configurato i rele remoti come mi hai indicato:

```
# Numero totale di elettrovalvole
EV_TOTAL=8
EV_MONOSTABLE=1

# SonOff A
EV1_ALIAS="SONOFF_A_RELE_1"
EV1_GPIO="drv:sonoff_tasmota_http:SONOFF1:Power1"
EV1_NORAIN=1

EV2_ALIAS="SONOFF_A_RELE_2"
EV2_GPIO="drv:sonoff_tasmota_http:SONOFF1:Power2"
EV2_NORAIN=1

EV3_ALIAS="SONOFF_A_RELE_3"
EV3_GPIO="drv:sonoff_tasmota_http:SONOFF1:Power3"
EV3_NORAIN=1

EV4_ALIAS="SONOFF_A_RELE_4"
EV4_GPIO="drv:sonoff_tasmota_http:SONOFF1:Power4"
EV4_NORAIN=1

# SonOff B
EV5_ALIAS="SONOFF_B_RELE_1"
EV5_GPIO="drv:sonoff_tasmota_http:SONOFF2:Power1"
EV5_NORAIN=1

EV6_ALIAS="SONOFF_B_RELE_2"
EV6_GPIO="drv:sonoff_tasmota_http:SONOFF2:Power2"
EV6_NORAIN=1

EV7_ALIAS="SONOFF_B_RELE_3"
EV7_GPIO="drv:sonoff_tasmota_http:SONOFF2:Power3"
EV7_NORAIN=1

EV8_ALIAS="SONOFF_B_RELE_4"
EV8_GPIO="drv:sonoff_tasmota_http:SONOFF2:Power4"
EV8_NORAIN=1

#
# Configurazione Sonoff remoti
#
SONOFF1_IP="192.168.0.203"
SONOFF1_USER=""
SONOFF1_PWD=""

SONOFF2_IP="192.168.0.204"
SONOFF2_USER=""
SONOFF2_PWD=""
```

Ho quindi pulito la directory "piGarden/log" ed eseguito il comando:

```
/home/pi/piGarden/piGarden.sh init
```

Il file di log però riporta degli errori:

```
lun 21 mag 2018, 09.15.44, CEST		Run initialize
lun 21 mag 2018, 09.15.44, CEST		Remote rele open error: Command error: 
lun 21 mag 2018, 09.15.44, CEST		Remote rele open error: Command error: 
lun 21 mag 2018, 09.15.45, CEST		Remote rele open error: Command error: 
lun 21 mag 2018, 09.15.45, CEST		Remote rele open error: Command error: 
lun 21 mag 2018, 09.15.45, CEST		Remote rele open error: Command error: 
lun 21 mag 2018, 09.15.45, CEST		Remote rele open error: Command error: 
lun 21 mag 2018, 09.15.45, CEST		Remote rele open error: Command error: 
lun 21 mag 2018, 09.15.46, CEST		Remote rele open error: Command error: 
lun 21 mag 2018, 09.15.46, CEST		Rain sensor initialized
lun 21 mag 2018, 09.15.46, CEST		End initialize
```

Purtroppo l'errore non è chiaro quindi non si capisce il motivo. Sarebbe utilie avere il log completo del comando inviato per capire dove sia il problema.

Nel file di configurazione sono presenti anche dei GPIO :

```
# Id gpio usati per simulare il doppio deviatore con cui eseguire l'alimentazione alle elettrovalvole
SUPPLY_GPIO_1=2
SUPPLY_GPIO_2=3

# Stato dei due gpio per impartire l'alimentazione positiva alle elettrovalvole (aperta)
SUPPLY_GPIO_POS=0

# Stato dei due gpio per impartire l'alimentazione negativa alle elettrovalvole (chiusa)
SUPPLY_GPIO_NEG=1

# Stato di ingresso da assegnare al gpio per chiudere il rele
RELE_GPIO_CLOSE=0

# Stato di ingresso da assegnare al gpio per aprire il rele
RELE_GPIO_OPEN=1

# Id del gpio usato per collegare il sensore di rilevamento pioggia
RAIN_GPIO=25		# Physical 22 - wPi 6

# Valore in ingresso sul gpio definito in RAIN_GPIO che indica lo stato di pioggia
RAIN_GPIO_STATE=0
```

Non ho capito bene ogni voce ma l'unico GPIO che effettivamente viene utilizzato è "Physical 22 - wPi 6" ? Se volessi escludere completamente la gestione dei GPIO come si procede ? 

Non ricordo le connessioni GPIO che ho utilizzato quindi per adesso vorrei escludere qualsiasi manovra sui GPIO per non avere problemi con altre periferiche che sono collegate.

> Non ho capito bene invece a cosa servono i due gruppi di piedini nominati N e GND.

La scheda ho solo rele "C e NA" la connessione "NC" non esiste. La connessione GND è la Terra.

Rimango in attesa di qualche riscontro.

**Comment by lejubila** [comment]
> Ho qualche minuti di tempo quindi ho installato la nuova versione ma ho dovuto utilizzare un altro comando per ottenre "piGarden":

Strano che non abbia funzionato, in teoria doveva portarti sul brench drv e poi aggiornare.
Comunque ho fatto varie correzioni e aggiunto più output nei log dei driver in caso di errore.

Dovresti aggiornare con 
`git pull`
sperando che questa volta funzioni.

Per quanto riguarda i gpio, gli unici che vengono definiti sono quelli usati per gestire l'inversione di polarità per l'elettrovalvole bistabili
```
SUPPLY_GPIO_1=2
SUPPLY_GPIO_2=3
```
ma dato che hai definito che sono presenti solo elettrovalvole monostabili (EV_MONOSTABLE=1) non c'é pericolo che i gpio 2 e 3 vengano utilizzati.

Attendo tue info.

**Comment by lejubila** [comment]
_From @debugasm on May 22, 2018 6:27_

Questa volta inviando il comando
```
git pull
```
ho ottenuto quello che dovevo, non chiedermi perchè precedentemente non ha funzionato:
```
remote: Counting objects: 7, done.
remote: Total 7 (delta 6), reused 7 (delta 6), pack-reused 0
Unpacking objects: 100% (7/7), done.
Da https://github.com/lejubila/piGarden
   3eb45fd..87edbbb  drv        -> origin/drv
Aggiornamento di 3eb45fd..87edbbb
Fast-forward
 drv/sonoff_tasmota_http/common.include.sh | 17 ++++++++++++-----
 drv/sonoff_tasmota_http/init.include.sh   |  2 +-
 drv/sonoff_tasmota_http/rele.include.sh   | 12 ++++++------
 3 files changed, 19 insertions(+), 12 deletions(-)
```
Naturalmente prima di aggiornarlo ho inviato il comando di "stop":
```
./piGarden.sh stop_socket_server
```
Ho cancellato il file di log e successivamente inviato il comando di inizializzazione per controllare eventuali errori:
```
./piGarden.sh init
```
Il file log riporta ancora gli errori ma con qualche informazione in più se può servire
```
mar 22 mag 2018, 08.22.00, CEST		Run initialize
mar 22 mag 2018, 08.22.00, CEST		Remote rele open error: Command error: {"POWER1":"OFF"}
mar 22 mag 2018, 08.22.00, CEST		Remote rele open error: Command error: {"POWER2":"OFF"}
mar 22 mag 2018, 08.22.00, CEST		Remote rele open error: Command error: {"POWER3":"OFF"}
mar 22 mag 2018, 08.22.01, CEST		Remote rele open error: Command error: {"POWER4":"OFF"}
mar 22 mag 2018, 08.22.01, CEST		Remote rele open error: Command error: {"POWER1":"OFF"}
mar 22 mag 2018, 08.22.02, CEST		Remote rele open error: Command error: {"POWER2":"OFF"}
mar 22 mag 2018, 08.22.02, CEST		check_rain_sensor - now it's raining (1526970122)
mar 22 mag 2018, 08.22.02, CEST		Remote rele open error: Command error: {"POWER3":"OFF"}
mar 22 mag 2018, 08.22.02, CEST		Remote rele open error: Command error: {"POWER4":"OFF"}
mar 22 mag 2018, 08.22.02, CEST		Rain sensor initialized
mar 22 mag 2018, 08.22.02, CEST		End initialize
```
A te la palla, non dovrebbe mancare molto.

**Comment by lejubila** [comment]
Il problema è che nel json il nome del relè non rispetta quello indicato nella chiamata tramite url, infatti uno è maiuscolo e l'altro è minuscolo.
Ho modificato il driver in modo che faccia una conversione uppercase sul nome del relè quando vado a controllare il valore nel json.
Riaggiorna con il solito 
`git pull`
e verifica se così ci sono miglioramenti.

Aspetto tue notizie.

**Comment by lejubila** [comment]
_From @debugasm on May 23, 2018 6:30_

Ho aggiornato e riprovato ma l'errore precedente sussiste, allego log del driver:
```
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_init
./piGarden.sh: riga 23: drv_sonoff_tasmota_http_init: comando non trovato
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power1
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power2
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power3
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power4
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF2:Power1
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF2:Power2
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF2:Power3
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF2:Power4
mer 23 mag 2018, 08.28.40, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF1:Power1
remote=SONOFF1
remote_alias=Power1
command=cmnd=Power1%20Off
url api sonoff: http://192.168.0.203/cm?cmnd=Power1%20Off
curl code response: 0
response={"POWER1":"OFF"}
result=null
error=Command error: {"POWER1":"OFF"}
mer 23 mag 2018, 08.28.41, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF1:Power2
remote=SONOFF1
remote_alias=Power2
command=cmnd=Power2%20Off
url api sonoff: http://192.168.0.203/cm?cmnd=Power2%20Off
curl code response: 0
response={"POWER2":"OFF"}
result=null
error=Command error: {"POWER2":"OFF"}
mer 23 mag 2018, 08.28.41, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF1:Power3
remote=SONOFF1
remote_alias=Power3
command=cmnd=Power3%20Off
url api sonoff: http://192.168.0.203/cm?cmnd=Power3%20Off
curl code response: 0
response={"POWER3":"OFF"}
result=null
error=Command error: {"POWER3":"OFF"}
mer 23 mag 2018, 08.28.41, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF1:Power4
remote=SONOFF1
remote_alias=Power4
command=cmnd=Power4%20Off
url api sonoff: http://192.168.0.203/cm?cmnd=Power4%20Off
curl code response: 0
response={"POWER4":"OFF"}
result=null
error=Command error: {"POWER4":"OFF"}
mer 23 mag 2018, 08.28.41, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF2:Power1
remote=SONOFF2
remote_alias=Power1
command=cmnd=Power1%20Off
url api sonoff: http://192.168.0.204/cm?cmnd=Power1%20Off
curl code response: 0
response={"POWER1":"OFF"}
result=null
error=Command error: {"POWER1":"OFF"}
mer 23 mag 2018, 08.28.42, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF2:Power2
remote=SONOFF2
remote_alias=Power2
command=cmnd=Power2%20Off
url api sonoff: http://192.168.0.204/cm?cmnd=Power2%20Off
curl code response: 0
response={"POWER2":"OFF"}
result=null
error=Command error: {"POWER2":"OFF"}
mer 23 mag 2018, 08.28.42, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF2:Power3
remote=SONOFF2
remote_alias=Power3
command=cmnd=Power3%20Off
url api sonoff: http://192.168.0.204/cm?cmnd=Power3%20Off
curl code response: 0
response={"POWER3":"OFF"}
result=null
error=Command error: {"POWER3":"OFF"}
mer 23 mag 2018, 08.28.42, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF2:Power4
remote=SONOFF2
remote_alias=Power4
command=cmnd=Power4%20Off
url api sonoff: http://192.168.0.204/cm?cmnd=Power4%20Off
curl code response: 0
response={"POWER4":"OFF"}
result=null
error=Command error: {"POWER4":"OFF"}
```
Magari è più di aiuto.

**Comment by lejubila** [comment]
Puoi verificare che versione di bash hai ?
lo fai con 
bash --version

grazie.

**Comment by lejubila** [comment]
_From @debugasm on May 23, 2018 8:37_

Ecco la versione:

```
GNU bash, versione 4.3.30(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2013 Free Software Foundation, Inc.
Licenza GPLv3+: GNU GPL versione 3 o successiva <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by lejubila** [comment]
Ok bash va bene.
Potresti verificare anche se hai l'eseguibile jq e se lanciandolo funziona ? Poi sempre per jq andrebbe verificato se il suo percorso corrisponde a quello assegnato nella variabile JQ del file di configurazione.

**Comment by lejubila** [comment]
_From @debugasm on May 23, 2018 12:8_

Seguendo al tua guida "jq" è stato compilato e installato correttamente.

Nella configurazione "piGarden.conf":
```
# Posizione js
JQ="/usr/local/bin/jq"
```
Controllando è effettivamente installato:
```
pi@user:~ $  ls -l /usr/local/bin/
totale 1088
-rws--x--x 1 root staff  92312 mag  4  2016 aurora
-rwsr-xr-x 1 root root   33336 ago  2  2017 gpio
-rwxr-xr-x 1 root staff 825632 mag 20 09:53 jq
-rwxr-xr-x 1 root staff  35097 ago  2  2017 miniterm.py
-rw-r--r-- 1 root staff  35989 ago  2  2017 miniterm.pyc
lrwxrwxrwx 1 root staff     29 apr 13  2016 pooler485 -> /var/www/comapps/pooler485.sh
-rws--x--x 1 root staff  78624 apr 10  2016 sdm120c
```
Come vedi è tutto in ordine.

Ho verificato che "jq" funzionasse seguendo la guida [ufficiale](https://stedolan.github.io/jq/tutorial/)
```
curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5' | jq '.[0]'
```
Funziona perfettamente restituendo solo il primo commit, come da tutorial.

Altre idee ?

Per verificare, non avendo a disposizione un sonoff, potresti scriverti due righe un qualche codice che conosci (bash, php, python, c, c#, ecc.) che simuli un Sonoff e risponda in quel modo.

Aspetto con fiducia.

**Comment by lejubila** [comment]
Ho eseguito ancora delle correzioni,
dovresti riaggiornare sempre con 
git pull
e riverificare.
Speriamo che questa sia la volta buona ;)

**Comment by lejubila** [comment]
_From @debugasm on May 24, 2018 6:37_

Sembra che questa volta ci siamo, ma c'è ancora un errore forse quello che volevi scrivere è rimasto sulla tastiera :
```
gio 24 mag 2018, 08.31.23, CEST		Run initialize
gio 24 mag 2018, 08.31.23, CEST		Solenoid 'SONOFF_A_RELE_1' close
gio 24 mag 2018, 08.31.24, CEST		Solenoid 'SONOFF_A_RELE_2' close
gio 24 mag 2018, 08.31.24, CEST		Solenoid 'SONOFF_A_RELE_3' close
gio 24 mag 2018, 08.31.24, CEST		Solenoid 'SONOFF_A_RELE_4' close
gio 24 mag 2018, 08.31.24, CEST		Solenoid 'SONOFF_B_RELE_1' close
gio 24 mag 2018, 08.31.25, CEST		Solenoid 'SONOFF_B_RELE_2' close
gio 24 mag 2018, 08.31.25, CEST		Solenoid 'SONOFF_B_RELE_3' close
gio 24 mag 2018, 08.31.25, CEST		Solenoid 'SONOFF_B_RELE_4' close
gio 24 mag 2018, 08.31.25, CEST		Rain sensor initialized
gio 24 mag 2018, 08.31.25, CEST		End initialize
```
Log del driver
```
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_init
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power1
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power2
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power3
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power4
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF2:Power1
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF2:Power2
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF2:Power3
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF2:Power4
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF1:Power1
remote=SONOFF1
remote_alias=Power1
command=cmnd=Power1%20Off
url api sonoff: http://192.168.0.203/cm?cmnd=Power1%20Off
curl code response: 0
response={"POWER1":"OFF"}
result="OFF"
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF1:Power2
remote=SONOFF1
remote_alias=Power2
command=cmnd=Power2%20Off
url api sonoff: http://192.168.0.203/cm?cmnd=Power2%20Off
curl code response: 0
response={"POWER2":"OFF"}
result="OFF"
gio 24 mag 2018, 08.31.24, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF1:Power3
remote=SONOFF1
remote_alias=Power3
command=cmnd=Power3%20Off
url api sonoff: http://192.168.0.203/cm?cmnd=Power3%20Off
curl code response: 0
response={"POWER3":"OFF"}
result="OFF"
gio 24 mag 2018, 08.31.24, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF1:Power4
remote=SONOFF1
remote_alias=Power4
command=cmnd=Power4%20Off
url api sonoff: http://192.168.0.203/cm?cmnd=Power4%20Off
curl code response: 0
response={"POWER4":"OFF"}
result="OFF"
gio 24 mag 2018, 08.31.24, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF2:Power1
remote=SONOFF2
remote_alias=Power1
command=cmnd=Power1%20Off
url api sonoff: http://192.168.0.204/cm?cmnd=Power1%20Off
curl code response: 0
response={"POWER1":"OFF"}
result="OFF"
gio 24 mag 2018, 08.31.24, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF2:Power2
remote=SONOFF2
remote_alias=Power2
command=cmnd=Power2%20Off
url api sonoff: http://192.168.0.204/cm?cmnd=Power2%20Off
curl code response: 0
response={"POWER2":"OFF"}
result="OFF"
gio 24 mag 2018, 08.31.25, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF2:Power3
remote=SONOFF2
remote_alias=Power3
command=cmnd=Power3%20Off
url api sonoff: http://192.168.0.204/cm?cmnd=Power3%20Off
curl code response: 0
response={"POWER3":"OFF"}
result="OFF"
gio 24 mag 2018, 08.31.25, CEST drv_sonoff_tasmota_http_rele_open arg:drv:sonoff_tasmota_http:SONOFF2:Power4
remote=SONOFF2
remote_alias=Power4
command=cmnd=Power4%20Off
url api sonoff: http://192.168.0.204/cm?cmnd=Power4%20Off
curl code response: 0
response={"POWER4":"OFF"}
result="OFF"
```
Come puoi notare l'errore
```
gio 24 mag 2018, 08.31.23, CEST drv_sonoff_tasmota_http_rele_init arg:drv:sonoff_tasmota_http:SONOFF1:Power1
./drv/sonoff_tasmota_http/rele.include.sh: riga 7: drv_remote_rele_open: comando non trovato
```
Controllando il codice
```
#
# Inizializzazione rele 
#
# $1 identificativo relè da inizializzare
#
function drv_sonoff_tasmota_http_rele_init {
	drv_remote_rele_open "$1"
}
```
Forse dovrebbe essere
```
#
# Inizializzazione rele 
#
# $1 identificativo relè da inizializzare
#
function drv_sonoff_tasmota_http_rele_init {
	drv_sonoff_tasmota_http_rele_open "$1"
}
```

**Comment by lejubila** [comment]
Si hai ragione. Avendo preso spunto da un altro driver mi sono dimenticato di cambiare nome alla funzione.
Appena posso correggo e aggiorno il repository. 
Ti faccio sapere appena ho fatto.

**Comment by lejubila** [comment]
@debugasm
ho corretto il nome della funzione errato.
Quando vuoi puoi aggiornare con il soluto git pull e verificare se è tutto ok.
Fammi sapere, così se tutto funziona sposto le modifiche sul branch principale.

**Comment by ghost** [comment]
Lavoro concluso con successo, complimenti. Direi che in poco tempo hai aggiunto una funzionalità molto carina. Ottimo lavoro. Nei prossimi giorni lo proverò e ti farò sapere se ci sono problemi. 

Ho notato un'altra cosa sulla dashboard di piGardenWeb, apro un "issue" nell'altra sezione. 

Per quanto riguarda "piGarden", ho pensato che questa applicazione potrebbe gestire anche una eventuale illuminazione del giardino e se presente qualche pompa per laghetto ecc. Visto che comunque sono controlli di tipo OFF/ON, gestibili già da subito, sarebbe divertente aggiungerli. Naturalmente nella dashboard di piGardenWeb sarebbe necessario cambiare le icone "irrigazione" in "lampadine/pompe".

E' soltanto una idea, immagino che anche tu come me abbia un lavoro e che questo sia puro duvertimento.

**Comment by lejubila** [comment]
> Lavoro concluso con successo, complimenti. Direi che in poco tempo hai aggiunto una funzionalità molto carina. Ottimo lavoro. Nei prossimi giorni lo proverò e ti farò sapere se ci sono problemi.

Bene, allora spetto tue notizie per capire se è tutto ok così poi pubblico le novità.

> Per quanto riguarda "piGarden", ho pensato che questa applicazione potrebbe gestire anche una eventuale illuminazione del giardino e se presente qualche pompa per laghetto ecc. Visto che comunque sono controlli di tipo OFF/ON, gestibili già da subito, sarebbe divertente aggiungerli. Naturalmente nella dashboard di piGardenWeb sarebbe necessario cambiare le icone "irrigazione" in "lampadine/pompe".
> 
> E' soltanto una idea, immagino che anche tu come me abbia un lavoro e che questo sia puro duvertimento

Le modifiche che suggerisci sono state chieste anche da altri. Invece di inserirle direttamente in piGarden, che sarebbe poco coerente, sto lavorando ad un'altro progetto ([piDomoticHome](https://github.com/lejubila/piDomoticHome)) che dovrebbe andare a sostituire l'interfaccia web di piGarden. Con questo dovrebbe essere possibile gestire diversi moduli tra cui [piGarden](https://github.com/lejubila/piGarden), [piGuardian](https://github.com/lejubila/piGuardian) e un altro modulo per gestire l'illuminazione e accensione/spegnimento dispositivi.
Il lavoro da fare è lungo e il tempo a disposizione è poco dato che come suggerivi ho anche un lavoro e una famiglia ;)

**Comment by ghost** [comment]
Confermo che tutto funziona egregiamente senza alcun problema.

Complimenti per l'ottima integrazione.

**Comment by lejubila** [comment]
Ho appena pubblicato la nuova aversione di piGarden contenente il driver.
Ho pubblicato anche il post introduttivo https://www.lejubila.net/2018/06/pigarden-0-5-7-gestisci-le-tue-elettrovalvole-con-i-moduli-sonoff-grazie-al-nuovo-driver-sonoff_tasmota_http/

Chiudo l'issue
