### ISSUE TITLE
API wunderground

### ISSUE THREAD

**Issue by marsp76** [lejubila/piGarden#13]
Ciao
complimenti per il lavoro！Purtroppo sul tuo blog non si riesce a scrivere e uso impropriamente questo canale.
Le API wunderground non sono più un servizio gratuito e volevo chiederti se è possibile sostituirla con quella di openweathermap.
grazie
Marco

**Comment by lejubila** [comment]
Ciao @marsp76 
intanto ho risolto il problema dei commenti sul mio blog, grazie per la segnalazione.
Per quanto riguarda le API di wunderground proprio non lo sapevo che non erano più disponibili gratuitamente. Questo è un bel impiccio. 
Appena ho un attimo vedo come integrare openweathermap, spero non comporti un grosso lavoro :(

Ti tengo aggiornato.

**Comment by marsp76** [comment]
Ciao e grazie per la solerzia nella risposta. 
Io sono veramente a zero in programmazione e cose simili anche se adoro questo mondo. 
Pensavo, ma dimmi se sbaglio,  non sarebbe possibile generare uno script dove si sceglie il servizio delle API (quindi consentendo anche la scelta di uno a pagamento) inserendo quindi i data (key, indirizzo web, etc) nel frontend di pigardenweb? 
Ho installato molte centraline per irrigazione, ma il tuo software è semplice e quindi ha un potenziale grandissimo in questo campo.

**Comment by lejubila** [comment]
Scusa il ritardo nella risposta,
sto portando avanti l'implementazione di openweathermap in modo che l'utente possa scegliere questo oppure wunderground e magari in futuro altri servizi. 
La configurazione viene fatta tutta sul file di configurazione di piGarden perché piGardenWeb è solo il frontend e i due software comunicano via socket server. 
A dire il vero avevo in mente di implementare la configurazione dello script anche da interfaccia web #3 ma il tempo scarseggia e quindi per ora rimane solo un idea.

**Comment by marsp76** [comment]
Ciao
Si dovrebbe avere più tempo per riuscire a dare maggior risalto alla parte web con configurazioni direttamente fatte online. 
Io capisco di metterci solo le idee e non la parte "fisica" che poi è la più onerosa, ma sono un convito del web e secondo me potrebbe essere poi la carta vincente per tutto il sistema, dando la possibilità a chiunque di poter usare e costruire la propria centralina di irrigazione ad una cifra veramente ridicola rispetto il mercato. 
Grazie per l'attenzione

**Comment by lejubila** [comment]
Con la versione 0.5.8 di piGarden è stato rilasciato il supporto a OpenWeatherMap

**Comment by marsp76** [comment]
Grazie per il  tuo lavoro

Marco
