### ISSUE TITLE
Gestione cron schedulazioni

### ISSUE THREAD

**Issue by CarloPSW** [lejubila/piGarden#14]
Ciao David,
stavo consultanto il progetto e il codice, e oltre farti i complimenti per quanto lo hai ingrandito, mi sono chiesto una cosa. Nelle schedulazioni si ha la possibilità di inserire praticamento tutto, un giorno del mese, tutti i mesi, un mese specifico ecc... però mi sono accorto che non è possibile internvenire su irrigazioni a giorni alterni senza che ciclicamente in maniera costante viene ripetuta l'irrigazione per due giorni (es: se imposto:LU-ME-VE-DO mi ritrovo che il giorno dopo a domenica è lunedì, quindi andrebbe il giorno consecutivo.) Ho pensato a come ovviare e credo che in modo veloce è possibile inserire, nell'area delle schedulazioni in piGardenWEB, due voci oltre ai giorni della settimana ovvero: "GIORNI DISPARI" E "GIORNI PARI". E nel codice farei un conteggio di questo tipo:

Giorni dispari:
0 0 1-31/2 * * command

Giorni pari:
0 0 2-30/2 * * command

Cosa ne pensi?

Ciao, grazie e compliementi ancora

**Comment by CarloPSW** [comment]
In alternativa si potrebbe fare il modulo, che forse è meglio, in questo modo:
#!/bin/bash
i=currentday
for i in $(seq 31);do
    if (( $i % 2 )); then
        echo $i is odd
    else
        echo $i is even
    fi
done

Che ne pensi?

**Comment by lejubila** [comment]
Ho rilasciato una nuova versione di piGardenWeb dove ho implementato il tuo suggerimento. 
Adesso del campo dei giorni del mese è possibile scegliere anche la voce "giorni dispari" o "giorni pari".

**Comment by CarloPSW** [comment]
Grazie mille!

Che file hai toccato? Come eseguo l'aggiornamento?

**Comment by CarloPSW** [comment]
Trovato... sorry. Recupero i file da pigardenweb e li sostituisco con i miei?

Grazie

**Comment by lejubila** [comment]
Per aggiornare ti basta impartire il comando
git pull
dalla directory di piGardenWeb

**Comment by CarloPSW** [comment]
Esatto... fatto. Stasera provo. Grazie.
Ho visto, in pigardenweb, un tuo post per la semplificazione delle schedulazioni. scrivo qui anche se non è corretto. Immagino che non hai approfondito, giusto?
