### ISSUE TITLE
Problema con sensore pioggia

### ISSUE THREAD

**Issue by Ivano62** [lejubila/piGarden#15]
In più di una occasione, quindi non in modo sistematico, si è verifica l'apertura di una zona (elettrovalvola) nonostante il sensore pioggia segnala lo stato di pioggia. Sembra che ciò si verifica sulla zona che determina l'aggionamento dello stato del sensore. Di seguito il log dell'ultima volta che si è verificato il problema, come si vede la Zona_1 è stata aperta nonostante il sensore segnalasse pioggia.
Nel log non trovo traccia del cambio stato del sensore di pioggia.

Fri  7 Sep 03:40:01 CEST 2018           check_rain_sensor - now is not raining
Fri  7 Sep 03:40:05 CEST 2018           Solenoid 'Zona_3' open
Fri  7 Sep 04:05:03 CEST 2018           Solenoid 'Zona_3' close
Fri  7 Sep 04:12:02 CEST 2018           check_rain_sensor - now is not raining
Fri  7 Sep 04:12:05 CEST 2018           Solenoid 'Zona_2' open
Fri  7 Sep 04:37:03 CEST 2018           Solenoid 'Zona_2' close
Fri  7 Sep 04:44:01 CEST 2018           check_rain_sensor - now is not raining
Fri  7 Sep 04:44:05 CEST 2018           Solenoid 'Zona_4' open
Fri  7 Sep 05:09:03 CEST 2018           Solenoid 'Zona_4' close
Fri  7 Sep 05:16:02 CEST 2018           check_rain_sensor - now it's raining (1536290162)
Fri  7 Sep 05:16:07 CEST 2018           Solenoid 'Zona_1' open
Fri  7 Sep 05:41:03 CEST 2018           Solenoid 'Zona_1' close
Fri  7 Sep 05:48:02 CEST 2018           check_rain_sensor - now it's raining (1536292082)
Fri  7 Sep 05:48:04 CEST 2018           Solenoid 'Siepe' not open for rain (sensor check)
Fri  7 Sep 05:58:03 CEST 2018           Solenoid 'Siepe' close
Fri  7 Sep 06:05:01 CEST 2018           check_rain_sensor - now it's raining (1536293101)
Fri  7 Sep 06:05:03 CEST 2018           Solenoid 'Giardino_SUD' not open for rain (sensor check)
Fri  7 Sep 06:30:04 CEST 2018           Solenoid 'Giardino_SUD' close

**Comment by lejubila** [comment]
Verifica che nel file di configurazione non sia impostato l'apposito flag per fare ignorare lo stato della pioggia per "Zona_1"
EV1_NORAIN=1 # Con questo impostato l'elettrovalvola EV1 ignora la pioggia, se fosse impostato lo devi togliere.

Fammi sapere se effettivamente è così-

**Comment by Ivano62** [comment]
Ti assicuro che non è così, anche perché se così fosse il sensore della pioggia non verrebbe testato. Ho un'altra zona impostata come dici e funziona regolarmente.

Grazie.

Ciao

--- Messaggio originale ---
Da:     David Bigagli <notifications@github.com>
Data:   10 settembre 2018 09:57:27
A:      lejubila/piGarden <piGarden@noreply.github.com>
Cc:     Ivano62 <i_fabii@hotmail.com>, Author <author@noreply.github.com>
Oggetto:        Re: [lejubila/piGarden] Problema con sensore pioggia (#15)


Verifica che nel file di configurazione non sia impostato l'apposito flag per fare ignorare lo stato della pioggia per "Zona_1"
EV1_NORAIN=1 # Con questo impostato l'elettrovalvola EV1 ignora la pioggia, se fosse impostato lo devi togliere.

Fammi sapere se effettivamente è così-

**Comment by lejubila** [comment]
Puoi farmi avere il file di configurazione e l'intero file di log e dirmi che versione hai di piGarden ?

**Comment by Ivano62** [comment]
La versione è 0.5.6.

In allegato i file chiesti.

Grazie.

Ciao
________________________________
Da: David Bigagli <notifications@github.com>
Inviato: lunedì 10 settembre 2018 15:07
A: lejubila/piGarden
Cc: Ivano62; Author
Oggetto: Re: [lejubila/piGarden] Problema con sensore pioggia (#15)


Puoi farmi avere il file di configurazione e l'intero file di log e dirmi che versione hai di piGarden ?

**Comment by Ivano62** [comment]
[piGarden.conf.txt](https://github.com/lejubila/piGarden/files/2368171/piGarden.conf.txt)
[piGarden.log.txt](https://github.com/lejubila/piGarden/files/2368172/piGarden.log.txt)

Ora dovrebbero esserci.

Ciao

**Comment by Ivano62** [comment]
Ho fatto come hai detto.

Devo fare un'altra segnalazione.

Ho appena aggiornato il mio raspberry, durante l'operazione è stato visualizzato l'alter:

apt-listchanges: News
---------------------

apache2 (2.4.25-3+deb9u5) stretch; urgency=medium

  * This package upgrades mod_http2 to the version from apache2 2.4.33. This
    fixes a lot of bugs and some security issues, but it also removes the
    support for using HTTP/2 when running with mpm_prefork. HTTP/2 support
    is only provided when running with mpm_event or mpm_worker.

 -- Stefan Fritsch <sf@debian.org>  Sat, 02 Jun 2018 09:51:46 +0200

ritieni che questo impatti sulla tua applicazione?

Te lo chiedo perché subito dopo ho provato una zona tramite interfaccia web, il comando di apertura funziona mentre quello di chiusura NO, nonostante venga visualizzato l'esito positivo della chiusura, anche sul log risulta tutto regolare. Ho dovuto eseguire lo script da sistema operativo per poter chiudere la zona.

Grazie di nuovo.

Ciao
________________________________
Da: David Bigagli <notifications@github.com>
Inviato: lunedì 10 settembre 2018 21:22
A: lejubila/piGarden
Cc: Ivano62; Author
Oggetto: Re: [lejubila/piGarden] Problema con sensore pioggia (#15)


I file non ci sono.
Penso che li puoi allegare scrivendo direttamente dall'interfaccia di github.

**Comment by lejubila** [comment]
Il problema è questa definizione nel file di configurazione:
NOT_IRRIGATE_IF_RAIN_SENSOR=3
in pratica impedisce l'irrigazione per soli 3 secondi dall'ultimo evento di pioggia.
Devi aumentare il valore con un tempo a tuo piacimento. Ricordati che il valore è espresso in secondi.

Per quanto riguarda l'aggiornamento della tua distribuzione non mi sembra ci sia niente di compromettente.

**Comment by Ivano62** [comment]
Il parametro indicato, se non erro, dovrebbe servire per una gestione statica del periodo post pioggia, credo in particolare quando viene utilizzata verifica online.

In uno scenario con la gestione dinamica, basata su un sensore per pioggia specifico per impianti di irrigazione, come nel mio caso, non è opportuno/necessario impostare un valore statico.

Visto quanto sopra, ho impostato un valore molto basso proprio per cercare di ridurre al minimo l'effetto indesiderato.

Aggiungo, che il funzionamento anomalo si verifica solo sulla prima zona e non sulle successive, benché il tempo trascorso sia molto superiore ai tre secondi impostati. Inoltre, sulla prima zona si verifica solo se il cambio di stato (not rain -> rain) avviene proprio in fase di apertura della zona stessa.

Ciao

P.S. mi sai dire qualcosa sulla segnalazione che ho fatto ieri in tarda serata? Grazie.


--- Messaggio originale ---
Da:     David Bigagli <notifications@github.com>
Data:   10 settembre 2018 22:30:21
A:      lejubila/piGarden <piGarden@noreply.github.com>
Cc:     Ivano62 <i_fabii@hotmail.com>, Author <author@noreply.github.com>
Oggetto:        Re: [lejubila/piGarden] Problema con sensore pioggia (#15)


Il problema è questa definizione nel file di configurazione:
NOT_IRRIGATE_IF_RAIN_SENSOR=3
in pratica impedisce l'irrigazione per soli 3 secondi dall'ultimo evento di pioggia.
Devi aumentare il valore con un tempo a tuo piacimento. Ricordati che il valore è espresso in secondi.

Per quanto riguarda l'aggiornamento della tua distribuzione non mi sembra ci sia niente di compromettente.

**Comment by Ivano62** [comment]
Scusa se torno a disturbarti, ma è solo per dirti che l'ultima segnalazione, quella relativa all'aggiornamento del raspberry ed il mancato funzionamento del comando close di una zona tramite interfaccia web, la puoi trascurare. Infatti, ho risolto e non dipendeva affatto dall atua applicazione.

Ciao

________________________________
Da: Ivano Fabii <i_fabii@hotmail.com>
Inviato: martedì 11 settembre 2018 19:33
A: lejubila/piGarden; lejubila/piGarden; David Bigagli
Cc: Author
Oggetto: Re: [lejubila/piGarden] Problema con sensore pioggia (#15)

Il parametro indicato, se non erro, dovrebbe servire per una gestione statica del periodo post pioggia, credo in particolare quando viene utilizzata verifica online.

In uno scenario con la gestione dinamica, basata su un sensore per pioggia specifico per impianti di irrigazione, come nel mio caso, non è opportuno/necessario impostare un valore statico.

Visto quanto sopra, ho impostato un valore molto basso proprio per cercare di ridurre al minimo l'effetto indesiderato.

Aggiungo, che il funzionamento anomalo si verifica solo sulla prima zona e non sulle successive, benché il tempo trascorso sia molto superiore ai tre secondi impostati. Inoltre, sulla prima zona si verifica solo se il cambio di stato (not rain -> rain) avviene proprio in fase di apertura della zona stessa.

Ciao

P.S. mi sai dire qualcosa sulla segnalazione che ho fatto ieri in tarda serata? Grazie.


--- Messaggio originale ---
Da:     David Bigagli <notifications@github.com>
Data:   10 settembre 2018 22:30:21
A:      lejubila/piGarden <piGarden@noreply.github.com>
Cc:     Ivano62 <i_fabii@hotmail.com>, Author <author@noreply.github.com>
Oggetto:        Re: [lejubila/piGarden] Problema con sensore pioggia (#15)


Il problema è questa definizione nel file di configurazione:
NOT_IRRIGATE_IF_RAIN_SENSOR=3
in pratica impedisce l'irrigazione per soli 3 secondi dall'ultimo evento di pioggia.
Devi aumentare il valore con un tempo a tuo piacimento. Ricordati che il valore è espresso in secondi.

Per quanto riguarda l'aggiornamento della tua distribuzione non mi sembra ci sia niente di compromettente.

**Comment by lejubila** [comment]
Rispondo dopo molto tempo.
Il problema è il valore inserito nella variabile NOT_IRRIGATE_IF_RAIN_SENSOR che deve superare i 5 minuti  (300).
Dato che il controllo del sensore pioggia viene eseguito ogni 5 minuti, mettere un valore più basso sarebbe inefficace. Per essere sicuri ti suggerisco di inserire una valore che superi i 5 minuti, tipo 400.
