### ISSUE TITLE
nuova funzionalità per gestione pioggia

### ISSUE THREAD

**Issue by androtto** [lejubila/piGarden#16]
ciao @david
sto pensando di cambiare il sensore pioggia in quanto quello impiegato finora misura la prima pioggia (e con il trimmer è possibile variarne la sensibilità), ma non effettivamente l’intensità delle precipitazioni. Quello che vorrei controllare è lo stop dell’irrigazione del prato solo se l’acqua della pioggia sia della quantità minima per far saltare il ciclo.
Ho trovato questo componente https://www.aliexpress.com/item/Spare-part-for-weather-station-to-measure-the-rain-volume-for-rain-meter-for-rain-gauge/2027467349.html
che ad ogni riempimento della vaschetta (misurando quindi una certa quantità d’acqua che possiamo ricondurre ad un XX mm di pioggia) invia un impulso al raspy. Ho trovato il comando (gpio falling) che attende il cambio di stato (da 1 normale a 0 – falling – al riempimento della vaschetta e poi ritorna a 1 -rising – in attesa di passare di nuovo a 0 – falling – e così via) e quindi con un loop di questo tipo posso misurare la quantità di acqua:

counter=0
while true
do
gpio -g wfi 25 falling
counter=$(( counter+=1 ))
gpio -g wfi 25 rising # magari basta uno sleep 1, da verificare
done

L’obiettivo è quindi quello di sostituire la funzione check_rain_sensor con quella in via di modifica al fine di rilevare la pioggia solo dopo un certo numero di vaschette riempite.
Mi hai scritto in un altro post di utilizzare la sottodirectory piGarden/drv per implementare quanto da me esposto.
Mi dai qualche dritta come fare?
Io stavo pensando di aggiungere una funzione nuova in /home/pi/piGarden/include/rain.include.sh e chiamarla in alternativa alla tua, usando lo stesso flag state/rain
Allo stesso tempo necessito di nuove variabili, tipo:
LOOPSFORSETRAINING=10 # dopo 10 impulsi, 10 vaschette riempite si considera pioggia
SECSBETWEENRAINEVENT=10800 # =3h, significa che dopo 3 si resetta il numero di vaschette da riempire e solo dopo il riempimento del numero di vaschette si considera una nuova pioggia
ad esempio, se alle h 10 inizia a piovere, dopo 10 loop - 10 vaschette alle h 10.30 si dichiara pioggia. se ci fosse entro 3 ore una nuova vaschetta (11° loop) allora il timestamp della pioggia viene aggiornato (significa che sta ancora piovendo) solo però se non sono passate 3 ore, altrimenti per determinare un nuovo evento pioggia devono precipitare almeno altre 10 vaschette di acqua
grazie
ciao
A

**Comment by androtto** [comment]
Ho trovato un articolo per calibrare lo strumento, ogni impulso misura 0,3 mm per impulso. Appena arriva l'aggeggio lo calibro e verifico quanto segue.
Direi che il raspy dovrà saltare l'irrigazione solo dopo almeno 10mm di pioggia, che fanno 10 litri di acqua su 1 mq, quindi - secondo quanto riportato - dopo almeno 33 impulsi il sistema dovrà segnalare la quantità di pioggia che determina l'evento pioggia.

Ecco l'articolo:
This is a very simple tipping-bucket type gauge, easily interfaced to most monitoring systems. There is a magnet on the moving bucket element which activates reed switch inside each time it tips, briefly shorting the two signal conductors. I just tied one side to ground (polarity doesn't matter) and the other to a microcontroller GPIO input, pulled up to 3.3V. As with any long cable leading outside, to help protect the MCU from lightning-induced surges it's a good idea to put as much resistance in series with each conductor as possible while still letting the sense input trigger reliably (I think I used 220 ohms on each side), along with a Zener diode to clamp excessive or negative voltages.

You do need to calibrate it by measuring the surface collection area, and putting in a controlled amount of water from a syringe, etc. while counting the pulses. I measured mine at 5cm x 11cm, and 6 pulses per 10mL => 10/6 = 1.67mL per pulse.

1mm rain = 0.1*5*11cm = 5.5 mL
1" rain = 2.54*5*11cm = 139.70 mL

@ 6 pulses per 10mL => 10/6 = 1.67mL per pulse

pulses / mm = 5.5 / (10/6) = 3.3
pulses / in = 139.7/(10/6) = 83.82

mm / pulse = 0.30303
in / pulse = 0.01193

or 83.82 pulses per inch of rain - reasonably good resolution for such an inexpensive instrument. Best to measure yours independently, though, just in case there's more than one variant.

Also, it's important that this type of rain gauge be mounted perfectly level, clear of any trees, buildings etc. and close to 5ft / 1.5m height to be in agreement with usual meteorological standards.

**Comment by lejubila** [comment]
Ho creato il nuovo branch "rainsensorqty"
Qui trovi lo scheletro del nuovo driver rainsensorqty.
Nel file drv/rainsensorqty/rainsensor.include.sh trovi a funzione drv_rainsensorqty_rain_sensor_get che viene invocata da check_rain_sensor. Li dentro puoi mettere il tuo codice. Puoi accedere alle variabili RAINSENSORQTY_LOOPSFORSETRAINING e RAINSENSORQTY_LOOPSFORSETRAINING che vanno precedentemente definite nel file di configurazione similmente a come indicato in conf/piGarden.conf.rainsensorqty.example. 
Nella funzione ho già inserito io un controllo per evitare il sovrapposizionamento di più chiamate alla stessa funzione dato che il controllo viene invocato una volta ogni minuto dal crontab.

Per abilitare l'utilizzo di questo driver per il controllo del sensore devi definire nel file di configurazione la variabile RAIN_GPIO in questo modo:
RAIN_GPIO="drv:rainsensorqty:25"

**Comment by androtto** [comment]
ciao @lejubila 
ho visto la struttura, ma non è possibile eseguire una funzione per capire se ha piovuto, il processo deve funzionare in backgroup in autonomia e al raggiungimento del riempimento delle vaschette (33) dichiara la pioggia.
la funzione check_rain_sensor non può fare una chiamata alla funzione che dovrei scrivere, anzi dovrebbe verificare direttamente la presenza del file status/rain 
in  pratica lo script la funzione initialize (lancio dello script piGarden.sh init) dovrebbe lanciare in nohup il daemon che monitora la vaschetta, in questo modo:
(ovviamente le varibili sono una bozza dei tentativi che ho fatto oggi):

        # esegue rainmonitor di RAINv2
        if [ -n "$RAINv2" ]; then
                log_write "RAINv2 sensor started"
                nohup "$DIR_SCRIPT/include/rainmonitor.sh" >> /tmp/andy 2>&1 &
                sleep 1
        else
                log_write "RAINv2 sensor not enabled"
        fi

come posso fare un git clone della nuova struttura che hai fatto?
grazie
ciao
A

**Comment by lejubila** [comment]
git clone https://github.com/lejubila/piGarden.git 
cd piGarden
git checkout rainsensorqty

Con l'ultimo comando passi nel brench rainsensorqty

**Comment by androtto** [comment]
Ottimo

Ci lavoro nei prossimi giorni.

Grazie

Ciao

A

**Comment by androtto** [comment]
Ciao David

Vediamo se ho capito.

Lo script piGarden.sh ad ogni avvio lancia la funzione setup_drv che dinamincamente include tutti i file contenenti *.include.sh

(più o meno quelli con nomi standard “for callback in config common init rele supply rainsensor rainonline setup”) nel mio caso i seguenti file - se la variabile è valorizzata così RAIN_GPIO="drv:rainsensorqty:25" :

pi@raspberrypi:~ $ ll piGarden/drv/rainsensorqty/

total 28

-rw-r--r-- 1 pi pi  190 Nov 13 21:00 common.include.sh

-rw-r--r-- 1 pi pi  132 Nov 12 18:17 config.include.sh

-rw-r--r-- 1 pi pi  405 Nov 13 21:09 init.include.sh

-rw-r--r-- 1 pi pi  830 Nov 12 18:17 rainsensor.include.sh

-rw-r--r-- 1 pi pi   38 Nov 12 18:17 README.md

-rw-r--r-- 1 pi pi  300 Nov 12 18:17 setup.include.sh

pi@raspberrypi:~ $

valorizzando le funzioni specifiche. Queste funzioni però devono essere note e chiamate nelle varie sezioni dello script, se necessario.

Vedo tre punti in cui le funzioni definite per drv:rainsensorqty :

*	all’avvio del raspy, attraverso la funzione inizialize nel corpo dello script principale – chiamata da piGarden.sh init - che deve eseguire il processo (lo script che loopa all’infinito) ogni reboot
*	ogni qualvolta lo script viene lanciato con l’opzione check_rain_sensor (piGarden.sh check_rain_sensor) viene chiamata la funzione check_rain_sensor definita da piGarden/include/rain.include.sh l

tale funzione dovrebbe esser in grado di lanciare drv_rainsensorqty_rain_sensor_get se RAIN_GPIO="drv:rainsensorqty:25" , ma questo non lo trovo:

pi@raspberrypi:~/piGarden/include $ grep rainsensorqty *

pi@raspberrypi:~/piGarden/include $

*	una verifica lo script di monitor sia sempre attivo

 

Ti spiego come dovrebbe funzionare:

*	init deve lanciare lo script col nohup, nella funzione initialize deve essere chiamata – se RAIN_GPIO="drv:rainsensorqty ... “ -  la funzione drv_rainsensorqty_init
*	lo script di monitor se trova la pioggia scrive il file "$STATUS_DIR/rainsensorqty_lastrain" con il momento della ultima pioggia (eventualmente lo aggiorna se continua a piovere)
*	lo funzione check_rain_sensor - se RAIN_GPIO="drv:rainsensorqty ... “ – deve verificare il contenuto in secondi dell’eventuale presenza del file "$STATUS_DIR/rainsensorqty_lastrain" (che non posso creare al setup altrimenti simuliamo la finta pioggia)

 

cosa ne pensi?

 

Per i seguenti file:

*	common.include.sh – contiene la funzione rainsensorqty_check per verificare che il processo di monitor sia attivo, restituisce 0 se è ok, 1 se non lo è – da lanciare quanto lo ritieni opportuno, ad esempio da check_rain_sensor
*	config.include.sh – usato e cambiato contenuto
*	init.include.sh – usato, serve per inizializzare la porta GPIO come input e fare partire il processo che loopa
*	rainsensor.include.sh – da te precompilato, non capisco per cosa, a me non serve
*	rainsensorqty_monitor.sh – script per monitorare il riempimento delle vaschette, deve essere sempre in attesa del cambio di stato
*	README.md – nessuna modifica per ora
*	setup.include.sh – non mi serve

 

ti allego alla mail i file tar della directory piGarden/drv/rainsensorqty , poi cerco di capire come spararli su git (non che sia così intuitivo).

 

ciao

 

Andrea

**Comment by androtto** [comment]
ciao a tutti
versione 0.1.1 in produzione!
qui il video: https://youtu.be/sOUBl1Dk_a0
ecco il package:
[rainsensorqty_v0.1.1_.tar.zip](https://github.com/lejubila/piGarden/files/2927776/rainsensorqty_v0.1.1_.tar.zip)

**Comment by lejubila** [comment]
Il nuovo driver per la gestione della pioggia è stato integrato in piGarden con la la versione 0.5.14.
