### ISSUE TITLE
Running solenoids consecutive 

### ISSUE THREAD

**Issue by Bigben83** [lejubila/piGarden#18]
Hi Lejubila,
this is an awesome system I have just discovered.  I have been using [https://github.com/rszimm/sprinklers_pi](url) for some years now but love your idea of using the sonoff relays, this makes it so easy to setup solenoid banks remotely.

what I do like about sprinklers_pi is the consecutive running of the programs so one starts after the other. and also the default setting of activating a pump when running any station.  as I have master solenoids on all my systems.

do you have any plans to implement this type of setup in your system ?

**Comment by lejubila** [comment]
Hi @Bigben83 ,
thank you for your interest.
Other users have asked me for a new feature similar to the one you ask. Surely in the future it will be implemented but I can not tell you exactly when.
However, you can work around this by using the piGarden event system. You can create a simple script and have it run when the ev_close_after event occurs. In the script you will check which solenoid valve has been closed and based on this you will start the next one.

With the following script we have four solenoids:
Solenoid_1
Solenoid_2
Solenoid_3
Solenoid_4

Starting Solenoid_1, at its end Solenoid_2 will be started, and so on until Solenoid_4.

```
#!/bin/bash
# /home/pi/piGarden/events/scripts/open_after_close.sh
# $1 = event
# $2 = alias solenoid
# $3 = time
#

EVENT="$1"
ALIAS="$2"
TIME=$3

if [ "$ALIAS" == "Solenoid_1" ]; then
	/home/pi/piGarden/piGarden.sh open_in 0 30 Solenoid_2
if [ "$ALIAS" == "Solenoid_2" ]; then
	/home/pi/piGarden/piGarden.sh open_in 0 30 Solenoid_3
if [ "$ALIAS" == "Solenoid_3" ]; then
	/home/pi/piGarden/piGarden.sh open_in 0 30 Solenoid_4
fi

```

To link the script to the event ev_close_after creates a symbolic link:

ln -s /home/pi/piGarden/events/scripts/open_after_close.sh /home/pi/piGarden/events/ev_close_after/


If you want more information on the system of events of piGarden you can look here
[https://www.lejubila.net/2017/11/pigarden-gestione-eventi/](https://www.lejubila.net/2017/11/pigarden-gestione-eventi/)
(unfortunately only in Italian)

**Comment by androtto** [comment]
Hi @Bigben83
please check here: 
[https://www.lejubila.net/2019/05/pigardensched-uno-schedulatore-alternativo-per-pigarden/](url)
It's possible scheduling one sprinkler after another.
Ciao
A
