### ISSUE TITLE
piGardenSched

### ISSUE THREAD

**Issue by androtto** [lejubila/piGarden#19]
ciao 
mi sono portato avanti con piGardenSched.
sono in beta test
Adesso il rapsy è acceso in test e sta funzionando senza problemi.
ho aggiunto un po' di funzioni (verificabili con help come opzioni) per modificare il file di configurazione /etc/piGarden.sched
appena hai tempo, se riusciamo a parlarne vediamo come finalizzare il progetto.
ciao
A
[piGardenSched_v0.1.4_.tar.zip](https://github.com/lejubila/piGarden/files/2927794/piGardenSched_v0.1.4_.tar.zip)

**Comment by androtto** [comment]
Ecco un po' di output (del log, del comando con un paio di opzioni):
pi@raspberrypi:~ /piGardenSched/log $ more piGardenSched.log
Mon Mar  4 00:28:00 CET 2019
Mon Mar  4 00:28:00 CET 2019 - START IRRIGATION ZONA1_pratoSud - no previous irrigation, this is the first one
EV ZONA1_pratoSud start irrigation
EV ZONA2_pratoSudOvest started in sequence after ZONA1_pratoSud
EV ZONA3_pratoNordOvest started in sequence after ZONA2_pratoSudOvest
EV ZONA4_pratoNord started in sequence after ZONA3_pratoNordOvest
EV ZONA1_pratoSud lastrun updated
EV ZONA1_pratoSud running nohup command /home/pi/piGardenSched/tmp/nohup_ZONA1_pratoSud_1.sh - check logfile /home/pi/piGardenSched/log/ZONA1_pratoSud_1_00:28.log
Mon Mar  4 00:40:00 CET 2019
Mon Mar  4 00:40:00 CET 2019 - START IRRIGATION Fragole - no previous irrigation, this is the first one
EV Fragole start irrigation
EV Fragole lastrun updated
EV Fragole running nohup command /home/pi/piGardenSched/tmp/nohup_Fragole_5.sh - check logfile /home/pi/piGardenSched/log/Fragole_5_00:40.log
Mon Mar  4 01:00:00 CET 2019
Mon Mar  4 01:00:00 CET 2019 - START IRRIGATION test - no previous irrigation, this is the first one
EV test start irrigation
EV test lastrun updated
EV test running nohup command /home/pi/piGardenSched/tmp/nohup_test_6.sh - check logfile /home/pi/piGardenSched/log/test_6_01:00.log
Tue Mar  5 00:28:00 CET 2019
EV ZONA1_pratoSud last irrigation was on Mon Mar  4 00:28:00 CET 2019
EV ZONA1_pratoSud next irrigation is on Thu Mar  7 00:28:00 CET 2019
Tue Mar  5 00:40:00 CET 2019
EV Fragole last irrigation was on Mon Mar  4 00:40:00 CET 2019
EV Fragole next irrigation is on Wed Mar  6 00:40:00 CET 2019
Tue Mar  5 01:00:00 CET 2019
EV test last irrigation was on Mon Mar  4 01:00:00 CET 2019
EV test next irrigation is on Thu Mar  7 01:00:00 CET 2019
pi@raspberrypi:~ /piGardenSched/log $ ../piGardenSched.sh stat
EV Fragole_5 - Mon Mar  4 00:40:00 CET 2019
EV test_6 - Mon Mar  4 01:00:00 CET 2019
EV ZONA1_pratoSud_1 - Mon Mar  4 00:28:00 CET 2019
pi@raspberrypi:~ /piGardenSched/log $ ../piGardenSched.sh show
#piGarden.sched config file
#author: androtto
#version 0.1.4
#format file
#1st field;2nd field;3rd field;4th field
#EV?_alias;duration;time;every_X_days
#EV?_alias;duration;EV?_previous
#time is HH:MM 24h format
#every_X_days means daily frequency, 1= every day, 2=every three days (first yes, second no)),3= every three days (first yes, second and third no), etc...
EV1_ALIAS;1;00:28;3
EV2_ALIAS;1;EV1_ALIAS;
EV3_ALIAS;1;EV2_ALIAS;
EV4_ALIAS;2;EV3_ALIAS;
EV5_ALIAS;1;00:40;2
EV6_ALIAS;1;01:00;3
pi@raspberrypi:~ /piGardenSched/log $

**Comment by androtto** [comment]
manca da sviluppare il ritardo dopo la pioggia.
nel senso che se l'irrigazione è ogni 3 giorni, e piove il secondo, l'irrigazione dovrebbe essere rimandata di un giorno

**Comment by androtto** [comment]
nuova versione praticamente ho rifatto tutto
[piGardenSched_v0.1.6.tar.zip](https://github.com/lejubila/piGarden/files/2959128/piGardenSched_v0.1.6.tar.zip)

**Comment by androtto** [comment]
ciao a tutti
ultimissima versione di PiGardenSched , la 0.3.0 
[piGardenSched_v0.3.0.tar.zip](https://github.com/lejubila/piGarden/files/3123195/piGardenSched_v0.3.0.tar.zip)

qualche candidato per i test?
ecco come attivarlo:
Nel package – da scompattare sotto la home dell’utente pi quindi /home/pi – vi è un file README che poi rimanda a piGardenSched/conf dove sono riportati i file.
Quindi: (dopo aver fatto unzip del file allegato)
```
cd /home/pi
tar xvf  piGardenSched_v0.3.0.tar
cd piGardenSched
more README
```
ciao
A

**Comment by lejubila** [comment]
Adesso piGardenSched ha il proprio repo https://github.com/lejubila/piGardenSched
Chiudo la issue
