### ISSUE TITLE
mcrypt richiede php 7.3

### ISSUE THREAD

**Issue by MatteoSid** [lejubila/piGarden#21]
mcrypt richiede al massimo la versione 7.3 di PHP ma l'ultima versione è la 7.3.4 quindi non si riesce a installare piGarden Web.
```
pecl/mcrypt requires PHP (version >= 7.2.0, version <= 7.3.0, excluded versions: 7.3.0), installed version is 7.3.4-2
No valid packages found
install failed
```

Basta sostituire la versione di PHP?

**Comment by lejubila** [comment]
In linea di massima direi di si. Personalmente non ho ancora provato con php 7.3.4.
Che versione di raspbian hai? 

Una piccola precisazione l'issue dovrebbe essere aperto su https://github.com/lejubila/piGardenWeb e non qui che è il progetto che si riferisce allo solo script bash.

**Comment by MatteoSid** [comment]
Ah giusto, scusami. Comunque ho l'ultimissima versione disponibile sul sito, ho preso un RBP B+ apposta per questo progetto ed ho installato l'ultima versione di Raspbian disponibile. Solo che non sono molto pratico di PHP e non avrei idea di come sostituire la versione corrente di PHP con l'ultima. 

Comunque complimenti per il progetto, un capolavoro!!!!!

**Comment by lejubila** [comment]
Ho aggiunto le istruzioni per eseguire l'installazione di piGardenWeb su Raspbian 10 Duster
https://github.com/lejubila/piGardenWeb/blob/master/README.md

prima di seguire le istruzioni disinstalla gli eventuali pacchetti php che hai già installato.
