### ISSUE TITLE
Aggiunta uscita per pompa

### ISSUE THREAD

**Issue by polcape** [lejubila/piGarden#5]
Complimenti per il progetto, veramente ottimo!
Apro la issue per proporre l'aggiunta di una funzione: un'uscita che permetta (tramite chiusura del relativo relè) l'accensione della pompa, utile nel caso di chi ha un pozzo.
Questa uscita dovrebbe attivarsi in corrispondenza di ogni schedulazione che riguardi almeno una elettrovalvola.

So che sarebbe già possibile farlo tramite workaround, ovvero tramite una finta elettrovalvola con schedulazione che corrisponda a ogni schedulazione impostata sulle altre, però averlo in modo diretto sarebbe veramente comodo.

**Comment by lejubila** [comment]
Ciao @polcape 
in questa [precedente issue](https://github.com/lejubila/piGarden/issues/2), avevo messo in programma la gestione di chiamate callback in base agli eventi scaturiti da piGarden.
Nel tuo caso allo scatenarsi dell'evento di apertura di una qualsiasi elettrovalvola potresti fare eseguire uno script custom il quale andrebbe a chiudere il relè che comanda l'accensione della pompa.
Pensi che potrebbe risolvere il tuo problema ?

**Comment by polcape** [comment]
Si, dovrei fare uno script a parte che invocato chiude un'altro relè collegato al raspberry, può essere un workaround più efficace di quello proposto prima.

A mio parere la soluzione migliore è che questa logica (relè che si accende quando almeno un altro è accesso) sia integrata in piGarden, perchè potrebbe capitare che uno abbia a monte un pozzo con pompa invece che la rete idrica. Valuta se può essere un buon suggerimento...

**Comment by polcape** [comment]
Grazie all'ultimo commit ho risolto il problema tramite la gestione eventi. Allego lo script che ho utilizzato, inserendolo in ev_close... o ev_open... e modificando il comportamento commentando/decommentando le sezioni necessarie per accensione/spegnimento pompa

Ho fatto in modo che si possa vedere lo stato del relè pompa censendolo in piGarden e aggiornandone lo stato tramite script

[gestionePompa.txt](https://github.com/lejubila/piGarden/files/1435146/gestionePompa.txt)

**Comment by lejubila** [comment]
Risolto con gestione eventi in puGarden v 0.5.2
