### ISSUE TITLE
Momorizzare log in un db

### ISSUE THREAD

**Issue by lejubila** [lejubila/piGarden#6]
al momento, se non erro, tutti gli eventi vengono registrati nel file di log piGarden.log, potrebbe essere utile a fini statistici, inserire alcuni di tali eventi (p.e. inizio e fine di una irrigazione, apertura e chiusura del rain sensor, ecc.) anche in una apposita tabella del database; questi dati potrebbero poi essere utilizzati per diversi scopi da che ne ha interesse

**Comment by alphagold** [comment]
Bella feature, per esempio secondo me utilissimo vedere sull'interfaccia web di piGardenWeb, l'ultima ora di attivazione dell'elettrovalvola, sopratutto in questi giorni di pioggia. Anche solo per sapere è partita o ha "saltato" per sensore o meteo web.

**Comment by sldp2k** [comment]
Ciao Lejubila, sto usando piGarden nel mio terreno ed è fanta.... concordo sia per l'utilità di avere dati su DB che di avere i dati in interfaccia piGardenWeb come detto da alphagold.  Grazie per il lavoro. Stef

**Comment by lejubila** [comment]
Feature implementata con piGardern 0.6.1 e piGardenWeb 0.6.0
